kind: pipeline
type: kubernetes
name: cicd-app-pipe

steps:
- name: clean
  image: python
  failure: ignore
  commands:
  - pytest
- name: publish
  image: plugins/docker
  settings:
   repo: cedricfe/cicd-app
   tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
   username:
     from_secret: DOCKERHUB_USERNAME
   password:
     from_secret: DOCKERHUB_PASSWORD
   trigger:
     branch:
     - master
#- name: notify
#  image: plugins/webhook
#  settings:
#    urls: https://webexapis.com/v1/webhooks/incoming/$TOKEN
#    content_type: application/json
#    template: |
#      {"markdown" : "**Status:**  Build {{build.number}} was {{build.status}}"}